"""Initial migration

Revision ID: 007a3d7de5a6
Revises: 
Create Date: 2026-04-26 12:50:11.386643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '007a3d7de5a6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_status',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sender_email', sa.String(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('classification', sa.String(), nullable=False),
    sa.Column('budget_estimation', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_status_is_processed'), 'lead_status', ['is_processed'], unique=False)
    op.create_table('project_sync_status',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clickup_task_id', sa.String(), nullable=True),
    sa.Column('folder_id', sa.String(), nullable=True),
    sa.Column('client_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_name', sa.String(), nullable=False),
    sa.Column('log_level', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_logs_service_name'), 'system_logs', ['service_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_logs_service_name'), table_name='system_logs')
    op.drop_table('system_logs')
    op.drop_table('project_sync_status')
    op.drop_index(op.f('ix_lead_status_is_processed'), table_name='lead_status')
    op.drop_table('lead_status')
    # ### end Alembic commands ###
